# -*- coding: utf-8 -*-
# 跨模块复用的官网公共句对照
COMMON_CELLS = {
    "Interface that provides an icon.": "提供图标的接口。",
    "An event which can be sent through the scene graph.": "可通过场景图发送的事件。",
    "A completable goal. Call Complete() to mark the quest as done and fire CompleteEvent.":
        "一个可完成的目标。调用 Complete() 把任务标记为完成并触发 CompleteEvent。",
    "Abstract base class for all quest rewards.": "所有任务奖励的抽象基类。",
    "Abstract base class for all quest objectives.": "所有任务目标的抽象基类。",
    "Whether HUD notifications play for this quest's granted/progress/completed moments.":
        "此任务的发放/进度/完成时刻是否播放 HUD 通知。",
    "Triggered when an item is added. Fires on this inventory, then propagates up to all ancestor inventories.":
        "物品被添加时触发。先在本物品栏触发，再向上传播到所有祖先物品栏。",
    "Add one or more category instances to help define and organize this item.":
        "添加一个或多个类别实例，帮助定义和组织此物品。",
    "Retrieve an object value or fail if value is not a json object":
        "取出对象值；value 不是 json 对象则失败。",
    "Lightweight tag explaining why an effect ended.": "说明效果为何结束的轻量标签。",
    "This input has met all required conditions and has successfully fired. Most of the time, you should bind to this event. Tuple payload: 0: the player generating this event 1: the value generated by the physical input":
        "此输入已满足全部触发条件并成功触发。多数情况下应绑定此事件。元组载荷：0——产生事件的玩家；1——物理输入产生的值。",
    "Interface that provides descriptive names or text.": "提供描述性名称或文本的接口。",
    "The entitlement type to grant.": "要授予的 entitlement 类型。",
    "Signaled when this objective is considered complete.": "此目标被判定完成时触发。",
    "Whether players may favorite this quest to the HUD quest tracker.": "玩家是否可把此任务收藏到 HUD 任务追踪器。",
    "Triggered when an item is equipped. Fires on this inventory, then propagates up to all ancestor inventories.":
        "物品被装备时触发。先在本物品栏触发，再向上传播到所有祖先物品栏。",
    "Broadcast when this item is equipped or unequipped.": "此物品被装备/卸下时广播。",
    "Retrieve an array value or fail if value is not a json array": "取出数组值；value 不是 json 数组则失败。",
    "This input has been canceled before activation. For example, if the key is released before a “Press and Hold” time threshold. Tuple payload: 0: the player generating this event 1: the value generated by the physical input 2: elapsed seconds since detection began":
        "此输入在激活前被取消——例如在「按住」时长阈值到达前松开按键。元组载荷：0——玩家；1——物理输入产生的值；2——检测开始后经过的秒数。",
}
