# -*- coding: utf-8 -*-
# Input（Verse.org）模块内容包
PACK = {
    "outdir": "01_Verse.org/080_Input", "module_slug": "versedotorg/input",
    "overview_title": "Input module", "overview_grade": "A",
    "overview_url": "https://dev.epicgames.com/documentation/fortnite/verse-api/versedotorg/input",
    "overview": {"zh": "玩家输入管理：按玩家开关输入映射、订阅输入事件、查询可用输入设备与当前输入方式。子模块 Gameplay/UI 提供常见界面的预设按键映射常量。"},
    "overview_data_rows": [
        ("Gameplay/HotbarMapping 〔无独立页面〕", "快捷栏（Hotbar）的预设按键映射。"),
        ("UI/MenuNavigationMapping 〔无独立页面〕", "菜单导航的预设按键映射。"),
        ("UI/NextTab 〔无独立页面〕", "「下一个标签页」的预设按键映射。"),
        ("UI/PreviousTab 〔无独立页面〕", "「上一个标签页」的预设按键映射。"),
        ("UI/NextPage 〔无独立页面〕", "「下一页」的预设按键映射。"),
        ("UI/PreviousPage 〔无独立页面〕", "「上一页」的预设按键映射。"),
        ("UI/Back 〔无独立页面〕", "「返回」的预设按键映射。"),
        ("UI/InventoryMenuMapping 〔无独立页面〕", "物品栏菜单的预设按键映射。"),
        ("UI/Use 〔无独立页面〕", "「使用」的预设按键映射。"),
        ("UI/Inspect 〔无独立页面〕", "「查看」的预设按键映射。"),
        ("UI/Sort 〔无独立页面〕", "「整理」的预设按键映射。"),
        ("UI/Drop 〔无独立页面〕", "「丢弃」的预设按键映射。"),
        ("UI/CraftingMenuMapping 〔无独立页面〕", "制作菜单的预设按键映射。"),
        ("UI/Craft 〔无独立页面〕", "「制作」的预设按键映射。"),
        ("UI/Favorite 〔无独立页面〕", "「收藏」的预设按键映射。"),
        ("UI/Scrap 〔无独立页面〕", "「拆解」的预设按键映射。"),
        ("UI/MapMenuMapping 〔无独立页面〕", "地图菜单的预设按键映射。"),
        ("UI/Track 〔无独立页面〕", "「追踪」的预设按键映射。"),
        ("UI/Reset 〔无独立页面〕", "「重置」的预设按键映射。"),
        ("UI/PlaceMarker 〔无独立页面〕", "「放置标记」的预设按键映射。"),
        ("UI/ToggleView 〔无独立页面〕", "「切换视图」的预设按键映射。"),
        ("UI/ZoomIn 〔无独立页面〕", "「放大」的预设按键映射。"),
        ("UI/ZoomOut 〔无独立页面〕", "「缩小」的预设按键映射。"),
        ("UI/TouchMapping 〔无独立页面〕", "触摸操作的预设按键映射。"),
        ("UI/PointerSelect 〔无独立页面〕", "「指针选择」的预设按键映射。"),
        ("UI/PointerZoom 〔无独立页面〕", "「指针缩放」的预设按键映射。"),
    ],
    "known_cells": {
        "TriggerActivationEvent :: This input has met all required conditions and has successfully fired. Most of the time, you should bind to this event. Tuple payload: 0: the player generating this event 1: the value generated by the physical input": "",
        "This input has met all required conditions and has successfully fired. Most of the time, you should bind to this event. Tuple payload: 0: the player generating this event 1: the value generated by the physical input":
            "此输入已满足全部触发条件并成功触发。多数情况下应绑定此事件。元组载荷：0——产生事件的玩家；1——物理输入产生的值。",
        "This input has been canceled before activation. For example, if the key is released before a “Press and Hold” time threshold. Tuple payload: 0: the player generating this event 1: the value generated by the physical input 2: elapsed seconds since detection began":
            "此输入在激活前被取消——例如在「按住」时长阈值到达前松开按键。元组载荷：0——玩家；1——物理输入产生的值；2——检测开始后经过的秒数。",
        "Detection has started for this input e.g. a required key is now held down. Note: TriggerActivationEvent may also occur this frame, but this event will always be fired first. BeginDetectEvent and EndDetectEvent will always fire, regardless of whether the input is successful or canceled. Tuple payload: 0: the player generating this event 1: the value generated by the physical input":
            "此输入的检测已开始，例如所需按键正被按住。注意：TriggerActivationEvent 也可能在本帧发生，但本事件总是先触发。无论输入最终成功或取消，BeginDetectEvent 与 EndDetectEvent 都会成对触发。元组载荷：0——玩家；1——物理输入产生的值。",
        "Detection for this input is still being processed. For example, a time threshold may not be met. Tuple payload: 0: the player generating this event 1: the value generated by the physical input 2: elapsed seconds since detection began":
            "此输入的检测仍在进行中——例如时长阈值尚未满足。元组载荷：0——玩家；1——物理输入产生的值；2——检测开始后经过的秒数。",
        "Detection has finished e.g. no required keys are now down. Will always fire as a pair with BeginDetectEvent. Tuple payload: 0: the player generating this event 1: elapsed seconds since detection began":
            "检测已结束，例如所需按键均已松开。总是与 BeginDetectEvent 成对触发。元组载荷：0——玩家；1——检测开始后经过的秒数。",
        "The player's current preferred input method, updated when the player switches between keyboard/mouse, gamepad, or touch.":
            "玩家当前偏好的输入方式；在键鼠、手柄、触摸之间切换时更新。",
        "The set of input device capabilities currently available to the player, updated at runtime as devices connect or disconnect.":
            "玩家当前可用的输入设备能力集合；设备连接/断开时实时更新。",
        "Adds the given input_mapping to the player, enabling the input_actions within it to be processed and execute events.":
            "把给定的 input_mapping 加到玩家身上，使其中的 input_action 得到处理并可触发事件。",
        "Removes the given input_mapping from the player, which will disable the input_actions within it from being processed and prevent them from executing events.":
            "把给定的 input_mapping 从玩家身上移除，其中的 input_action 不再处理、不再触发事件。",
        "Returns the input_events object for the given input_action, allowing you to bind to events for this action.":
            "返回给定 input_action 的 input_events 对象，可绑定该动作的事件。",
        "World space position of the camera (the ray's origin). This is the camera eye point, not the near plane — a trace starting here may intersect geometry between the camera and the near plane that is not visible on screen. Use collision filtering to ignore the player pawn, or advance the start point along Direction past the near clip distance.":
            "相机的世界空间位置（射线起点）。这是相机眼睛点而非近裁剪面——从这里开始的检测可能撞上相机与近裁剪面之间屏幕上不可见的几何体。建议用碰撞过滤忽略玩家角色，或把起点沿 Direction 前移越过近裁剪距离。",
        "Normalized world space direction vector of the ray, pointing from the camera through the given viewport coordinate into the scene.":
            "射线的归一化世界空间方向：从相机穿过给定视口坐标指向场景。",
        "Flags for input devices currently available to the player. Updates at runtime as devices connect or disconnect.":
            "玩家当前可用输入设备的标志位。设备连接/断开时实时更新。",
        "Turn input mappings on or off for that player with 'AddInputMapping' and 'RemoveInputMapping'.":
            "用 AddInputMapping / RemoveInputMapping 为该玩家开启或关闭输入映射。",
    },
    "entries": {
        "versedotorg/input/available_input_devices": {"zh": "玩家当前可用输入设备的标志位；设备连接/断开时实时更新。"},
        "versedotorg/input/input_events/input_events(t)": {"zh": "用户输入事件的容器，可订阅其中的事件；通过 GetPlayerInput / GetInput 获取。",
            "example": 'IE := GetPlayerInput[P].GetInputEvents[int]()\nIE.PressedEvent.Subscribe(OnKeyPressed)'},
        "versedotorg/input/player_input": {"zh": "每个玩家一个的输入管理器：用 GetPlayerInput 获取，然后 AddInputMapping/RemoveInputMapping 开关该玩家的输入映射。"},
        "versedotorg/input/deproject_results": {"zh": "保存视口坐标反投影得到的世界空间射线。"},
        "versedotorg/input/getplayerinput": {"zh": "访问玩家的输入相关数据与设置。",
            "example": 'if (PI := GetPlayerInput[P]):\n    PI.AddInputMapping(MyMapping)'},
        "versedotorg/input/input_events": {"zh": "参数化构造：按输入值类型 t 创建 input_events 容器。"},
        "versedotorg/input/input_method": {"zh": "表示玩家当前偏好的输入方式（键鼠/手柄/触摸等）。"},
    },
}
