# -*- coding: utf-8 -*-
# Progression（Verse.org）模块内容包
PACK = {
    "outdir": "01_Verse.org/050_Progression", "module_slug": "versedotorg/progression",
    "overview_title": "Progression module", "overview_grade": "B",
    "overview_url": "https://dev.epicgames.com/documentation/fortnite/verse-api/versedotorg/progression",
    "overview": {"zh": "任务（quest）系统：定义可完成的目标，管理参与者与其成员关系，完成任务时触发事件。"},
    "entries": {
        "versedotorg/progression/quest_participant_info": {"zh": "描述参与者与任务之间的关系。"},
        "versedotorg/progression/quest_membership": {"zh": "把任务与参与者及其参与信息绑定在一起的记录。"},
        "versedotorg/progression/join_quest_error": {"zh": "参与者无法加入任务时返回的错误。"},
        "versedotorg/progression/abandon_quest_error": {"zh": "参与者无法放弃任务时返回的错误。"},
        "versedotorg/progression/quest": {"zh": "一个可完成的目标。调用 Complete() 把任务标记为完成并触发 CompleteEvent。"},
        "versedotorg/progression/quest_collection": {"zh": "任务参与关系的唯一事实来源（source of truth）。"},
        "versedotorg/progression/quest_participant": {"zh": "任务参与者的抽象基类。"},
        "versedotorg/progression/agent_quest_participant": {"zh": "以代理（agent）为载体的任务参与者——玩家、NPC、AI 等都适用。"},
    },
    "known_cells": {
        "Can this participant make progress on the quest.": "该参与者能否在此任务上取得进展。",
        "The quest this membership belongs to.": "此成员关系所属的任务。",
        "Signaled when a participant joins this quest.": "有参与者加入此任务时触发。",
        "Signaled when a participant joins any quest in this collection.": "有参与者加入此集合中任一任务时触发。",
        "Signaled when this participant joins a quest.": "此参与者加入任务时触发。",
        "Abstract base class for quest participants.": "任务参与者的抽象基类。",
        "Can this participant observe quest state.": "该参与者能否观察任务状态。",
        "The participant in this membership.": "此成员关系中的参与者。",
        "Signaled when a participant abandons this quest.": "有参与者放弃此任务时触发。",
        "Signaled when a participant abandons any quest in this collection.": "有参与者放弃此集合中任一任务时触发。",
        "Signaled when this participant abandons a quest.": "此参与者放弃任务时触发。",
        "Can this participant receive rewards on quest completion.": "任务完成时该参与者能否获得奖励。",
        "The participation info describing this participant's role.": "描述此参与者角色的参与信息。",
        "Signaled when this quest completes.": "此任务完成时触发。",
        "Signaled when any quest in this collection completes.": "此集合中任一任务完成时触发。",
        "Signaled when a quest this participant is in completes.": "此参与者所在的任务完成时触发。",
        "The agent this participant represents.": "此参与者所代表的代理。",
        "Marks this quest as completed. Fires CompleteEvent. Idempotent — no-op if already completed.":
            "把任务标记为完成并触发 CompleteEvent。幂等：已完成时无操作。",
        "All memberships indexed by quest.": "按任务索引的全部成员关系。",
        "Succeeds if this quest is completed.": "此任务已完成则成功。",
        "All memberships indexed by participant.": "按参与者索引的全部成员关系。",
        "Adds 'Participant' to 'Quest' with the given participation info.": "以给定的参与信息把 Participant 加入 Quest。",
        "Removes 'Participant' from 'Quest'.": "把 Participant 从 Quest 中移除。",
    },
}
