# -*- coding: utf-8 -*-
# SceneGraph 模块内容包
PACK = {
    "outdir": "01_Verse.org/040_SceneGraph", "module_slug": "versedotorg/scenegraph",
    "overview_title": "SceneGraph module", "overview_grade": "S",
    "overview_url": "https://dev.epicgames.com/documentation/fortnite/verse-api/versedotorg/scenegraph",
    "overview": {"zh": "SceneGraph 是「实体＋组件」的下一代场景对象模型：entity 是节点，行为与数据挂在 component 上，transform_component 决定位置，辅以相机、灯光、碰撞、交互、骨骼动画等组件族。"},
    "overview_data_rows": [
        ("GlobalModifierPosition", "（无独立页面）全局修饰符位置常量。"),
        ("VisualModifierPosition", "（无独立页面）视觉修饰符位置常量。"),
    ],
    "known_prefix": [
        ["Represents the physical body, lens of the camera and other cinematographic qualities",
         "表示相机的物理机身、镜头及其他电影摄影属性（传感器尺寸、宽高比锁定、焦距、对焦距离、位置等）。"],
        ["Base class for light components in the SceneGraph. Dependencies: transform_component on the entity positions the light.",
         "SceneGraph 中灯光组件的基类。依赖：实体上的 transform_component 决定灯的位置。"],
        ["Collision Volumes represent the collision shapes of meshes.",
         "碰撞体积：表示网格的碰撞形状，可被 Overlap/Sweep 查询检测，并在物理模拟中产生碰撞。"],
        ["The source component and volume (query input). For compound inputs (like an entity hierarchy) this will be a component/volume in that hierarchy. The SourceTransform is the transform of SourceVolume used for the overlap test. For single volume inputs like a sphere, the Source volume and transform are just the inputs to the overlap test, and the component is false.",
         "来源组件与体积（查询输入）。对复合输入（如实体层级），这是层级中参与查询的组件/体积；SourceTransform 是本次 Overlap 测试所用 SourceVolume 的变换。对球体等单体积输入，体积与变换即查询输入本身，component 为 false。"],
        ["The source component and volume (query input). For compound inputs (like an entity hierarchy) this will be a component/volume in that hierarchy. The SourceGlobalTransform is the transform of SourceVolume at the start of the sweep. For single volume inputs like a sphere, the volume and transform are just the inputs to the sweep, and the component is false.",
         "来源组件与体积（查询输入）。对复合输入（如实体层级），这是层级中参与查询的组件/体积；SourceGlobalTransform 是扫掠开始时 SourceVolume 的变换。对球体等单体积输入，体积与变换即查询输入本身，component 为 false。"],
    ],
    "known_cells": {
        "Whether the light should cast any shadows.": "此灯是否投射阴影。",
        "Every volume has a collision channel as part of its collision_profile. It is used to determine how two volumes interact.":
            "每个体积都在其 collision_profile 中带有碰撞通道，用于决定两个体积如何交互。",
        "Enable/disable collision on this volume.": "启用/禁用此体积的碰撞。",
        "Enable/disable spatial queries against this volume.": "启用/禁用对此体积的空间查询。",
        "Get the transform of this volume in the space of its owner (usually a component on an entity)":
            "获取此体积在所有者空间（通常是实体上的组件）中的变换。",
        "Set the transform of this volume in the space of its owner (usually a component on an entity)":
            "设置此体积在所有者空间中的变换。",
        "Base class for an animation easing function.": "动画缓动函数的基类。",
        "Cubic bezier easing function. See CubicBezierEasingFunctions for some basic easing values.":
            "三次贝塞尔缓动函数。基础缓动值参见 CubicBezierEasingFunctions。",
        "Succeeds if the component is enabled, fails if it's disabled.": "组件处于启用状态则成功，禁用则失败。",
        "Used to handle general interaction.": "用于处理通用交互。",
        "Implemented by classes whose instances can be enabled and disabled.": "由「实例可被启用/禁用」的类实现。",
        "Configurable blend between two camera modes": "两种相机模式之间的可配置混合。",
        "Rarity may be used by gameplay and presentation systems to classify and rank things.": "稀有度：供玩法与表现系统对事物进行分类与分级。",
        "Controls how the animation plays back.": "控制动画的播放方式。",
        "The collision channel for the owning object.": "所属对象的碰撞通道。",
        "Width of camera sensor in millimeters.": "相机传感器宽度（毫米）。",
        "Height of camera sensor in millimeters.": "相机传感器高度（毫米）。",
        "Horizontal offset of camera sensor.": "相机传感器的水平偏移。",
        "Vertical offset of camera sensor.": "相机传感器的垂直偏移。",
        "The camera sensor sensitivity to light.": "相机对光的感光度。",
        "Camera shutter speed.": "相机快门速度。",
        "Focal length of the lens in millimeters.": "镜头焦距（毫米）。",
        "Aperture of the lens in FStop.": "镜头光圈（FStop）。",
        "Squeeze factor for anamorphic lenses.": "变形（anamorphic）镜头的挤压系数。",
        "Number of blades of diaphragm.": "光圈叶片数。",
        "Sets the duration of the camera transition": "设置相机过渡的时长。",
        "The number of seconds after a successful interaction, before being able to initiate a subsequent interaction for anyone. This is only used if duration is greater than 0.0. Modifying this does not affect the RemainingDuration. When a cooldown starts on the component all other interactions are canceled.":
            "成功交互后、任何人都可再次发起交互之前所需的秒数。仅在 duration > 0.0 时生效；修改它不影响 RemainingDuration。组件开始冷却时，其上的所有其他交互都会被取消。",
        "The remaining cooldown, in seconds, before new interactions can be initiated on this component.":
            "此组件上可再次发起新交互前的剩余冷却秒数。",
        "Event which fires when the shared cooldown expires.": "共享冷却到期时触发的事件。",
        "The duration in seconds after a successful interaction, before the interacting agent can initiate a subsequent interaction. This is only used if the duration is greater than 0.0. Modifying this does not affect any RemainingPerAgentCooldownDuration. This property gives other agents time to interact, when there is a limited number of Simultaneous Interactors.":
            "成功交互后、发起交互的代理可再次发起交互之前所需的秒数。仅在 duration > 0.0 时生效；修改不影响 RemainingPerAgentCooldownDuration。当可同时交互人数有限时，此属性给其他代理留出交互时间。",
        "The cooldown remaining, in seconds, before a particular agent is able to initiate an interaction on this component.":
            "特定代理在此组件上可再次发起交互前的剩余冷却秒数。",
        "Event which fires when the per agent cooldown expires. Sends the agent which was previously affected by the cooldown.":
            "按代理的冷却到期时触发；载荷为此前受冷却影响的代理。",
        "The number of seconds an agent must spend interacting with the object to successfully complete an interaction. 0.0 or less results in an immediate successful interaction. If set during an interaction, the value given will be used for the next interaction and the remaining duration will be updated subtracting the new given value with the current time elapsed. If the subtraction were zero or less it will immediately conclude.":
            "代理需与对象持续交互这么多秒才能完成一次交互；≤0.0 表示立即成功。若在交互进行中设置，新值将用于下一次交互，剩余时长按「新值减去已用时间」更新；差值 ≤0 则立即结束。",
        "The max number of simultaneous interactors. A value of false is unlimited. This value represents how many agents may have active interactions. If this changes to a value less than the current number of active interactions, those interactions are not canceled but new interactions will not start.":
            "可同时交互的最大人数；false 表示不限。表示有多少代理可同时处于交互中。若改成小于当前活跃交互数的值，已有交互不取消，但不会开始新交互。",
        "Returns an agent’s remaining duration, in seconds, for interaction. Fails if the agent is not interacting with this component.Returns the same value when called multiple times within a transaction.":
            "返回某代理本次交互的剩余秒数；该代理未在交互则失败。同一事务内多次调用返回相同值。",
        "Sets an agent’s remaining duration, in seconds, for interaction. Fails if the agent is not interacting with this component.":
            "设置某代理本次交互的剩余秒数；该代理未在交互则失败。",
        "The number of times the component can be successfully interacted with. A value of false is unlimited. When SuccessfulInteractionCount reaches MaxSuccessfulInteractions all active interactions are canceled, and the component cannot be interacted with.":
            "此组件可被成功交互的次数；false 表示不限。达到 MaxSuccessfulInteractions 后所有活跃交互被取消，组件无法再被交互。",
        "The number of times this component has had a successful interaction.": "此组件已成功交互的次数。",
        "Resets the counter for the times this component has had a successful interaction.": "重置成功交互次数计数。",
        "The source volume (query input)": "来源体积（查询输入）",
        "The source volume transform": "来源体积变换",
        "The component that was hit by SourceVolume": "被 SourceVolume 命中的组件",
        "The volume that was hit by SourceVolume": "被 SourceVolume 命中的体积",
        "The source volume (query input).": "来源体积（查询输入）。",
        "The source volume transform at the start of the sweep.": "扫掠开始时来源体积的变换。",
        "The world-space translation (relative to SourceStartGlobalTransform) of SourceVolume when it touches TargetVolume.":
            "SourceVolume 触到 TargetVolume 时的世界位移（相对 SourceStartGlobalTransform）。",
        "The Distance along the sweep at which SourceVolume touches TargetVolume.": "扫掠路径上 SourceVolume 触到 TargetVolume 处的距离。",
        "The component that was hit by SourceVolume.": "被 SourceVolume 命中的组件。",
        "The volume that was hit by SourceVolume.": "被 SourceVolume 命中的体积。",
        "The point of contact between SourceVolume and TargetVolume.": "SourceVolume 与 TargetVolume 的接触点。",
        "The normal on TargetVolume at the HitPosition.": "HitPosition 处 TargetVolume 的法线。",
    },
    "entries": {
        "versedotorg/scenegraph/basic_interactable_component": {"zh": "具有可组合特性集的交互组件。"},
        "versedotorg/scenegraph/interactable_component": {"zh": "用于处理通用交互。"},
        "versedotorg/scenegraph/interactable_cooldown": {"zh": "设置交互后的冷却。"},
        "versedotorg/scenegraph/interactable_cooldown_per_agent": {"zh": "按代理分别设置交互冷却。"},
        "versedotorg/scenegraph/interactable_duration": {"zh": "设置一次交互的持续时长。"},
        "versedotorg/scenegraph/interactable_success_limit": {"zh": "设置可成功交互的次数上限。"},
        "versedotorg/scenegraph/camera_body": {"zh": "相机机身设置，如传感器/胶片、快门速度等。"},
        "versedotorg/scenegraph/camera_component": {"zh": "表示相机的物理机身、镜头及其他电影摄影属性：传感器尺寸、宽高比锁定/约束、焦距、对焦距离、位置等。"},
        "versedotorg/scenegraph/camera_director_component": {"zh": "负责在活动相机变化时选择相机并进行混合；还可在不同相机之间共享全局设置（如后期处理设置）。"},
        "versedotorg/scenegraph/camera_lens": {"zh": "相机镜头设置。"},
        "versedotorg/scenegraph/camera_modifier_stack": {"zh": "相机状态的修饰符栈。"},
        "versedotorg/scenegraph/camera_modifier": {"zh": "可修改相机状态的对象的基类。"},
        "versedotorg/scenegraph/camera_state": {"zh": "相机的当前状态。"},
        "versedotorg/scenegraph/camera_transition": {"zh": "控制相机模式之间如何过渡。"},
        "versedotorg/scenegraph/camera_mode_blend": {"zh": "两种相机模式之间的可配置混合。"},
        "versedotorg/scenegraph/camera_mode_blend_pop": {"zh": "瞬间切换（snap）到目标模式。"},
        "versedotorg/scenegraph/camera_mode_blend_linear": {"zh": "相机模式之间的线性混合。"},
        "versedotorg/scenegraph/camera_mode_blend_smoothstep": {"zh": "使用 smoothstep 函数在两种相机模式之间混合。"},
        "versedotorg/scenegraph/camera_mode_blend_smootherstep": {"zh": "使用 smootherstep 函数在两种相机模式之间混合。"},
        "versedotorg/scenegraph/camera_mode_blend_orbit": {"zh": "两种相机模式之间的可配置混合（orbit 轨道变体）。"},
        "versedotorg/scenegraph/orthographic_camera_component": {"zh": "简单的正交相机。"},
        "versedotorg/scenegraph/perspective_camera_component": {"zh": "简单的透视相机。"},
        "versedotorg/scenegraph/physical_camera_component": {"zh": "基于物理的相机：以更接近真实物理相机的方式决定取景属性。"},
        "versedotorg/scenegraph/camera_projection_mode": {"zh": "相机投影模式（正交/透视等）。"},
        "versedotorg/scenegraph/camera_transition_initial_orientation": {"zh": "控制相机模式过渡时的初始朝向。"},
        "versedotorg/scenegraph/has_camera_modifier": {"zh": "拥有相机修饰符栈的类实现的接口。"},
        "versedotorg/scenegraph/skeletal_animation": {"zh": "骨架的修饰符：用骨骼动画驱动网格变形。"},
        "versedotorg/scenegraph/play_skeletal_animation_result": {"zh": "播放骨骼动画的结果。"},
        "versedotorg/scenegraph/skeleton": {"zh": "骨架（skeleton）是骨骼与骨骼组/链（sets/chains）的集合。"},
        "versedotorg/scenegraph/capsule_light_component": {"zh": "胶囊灯：从指定半径与长度的胶囊形光源向场景四周发光；半径与长度为 0 时等效于点光源。"},
        "versedotorg/scenegraph/directional_light_component": {"zh": "方向光：模拟来自无限远处的光源，投射的阴影相互平行。"},
        "versedotorg/scenegraph/light_component": {"zh": "SceneGraph 中灯光组件的基类。依赖：实体上的 transform_component 决定灯的位置。"},
        "versedotorg/scenegraph/rect_light_component": {"zh": "矩形面光灯：从指定宽高的矩形平面向场景发光，可用于模拟各类面光源。"},
        "versedotorg/scenegraph/sphere_light_component": {"zh": "球形灯：从指定半径的球形光源向四周发光；半径为 0 时为点光源。"},
        "versedotorg/scenegraph/spot_light_component": {"zh": "聚光灯：从单点按锥形发光；锥形由内锥角（InnerConeAngleDegrees）与外锥角（OuterConeAngleDegrees）定义。"},
        "versedotorg/scenegraph/collision_channel": {"zh": "碰撞通道：每个体积都在其 collision_profile 中带有碰撞通道，用于决定两个体积如何交互。"},
        "versedotorg/scenegraph/collision_profile": {"zh": "碰撞轮廓：决定体积在 Overlap 查询、Sweep 查询与物理模拟中如何与其他体积交互。"},
        "versedotorg/scenegraph/overlap_hit": {"zh": "Overlap 查询的结果：SourceVolumes 中任一体积与其他体积的每个相交各产生一个 overlap_hit。见 entity.FindOverlapHits()。"},
        "versedotorg/scenegraph/sweep_hit": {"zh": "Sweep 查询的结果：每个相交产生一个 sweep_hit。见 entity.FindSweepHits()。"},
        "versedotorg/scenegraph/collision_volume": {"zh": "碰撞体积：表示网格的碰撞形状，可被 Overlap/Sweep 查询检测，并在物理模拟中产生碰撞。"},
        "versedotorg/scenegraph/collision_element": {"zh": "由单一体积＋单一 collision_profile 与 collision_material 构成的碰撞体积基类，覆盖大多数体积类型。"},
        "versedotorg/scenegraph/collision_capsule": {"zh": "沿 Z 轴对齐的碰撞胶囊体。"},
        "versedotorg/scenegraph/collision_sphere": {"zh": "碰撞球体。"},
        "versedotorg/scenegraph/collision_point": {"zh": "碰撞点。"},
        "versedotorg/scenegraph/collision_box": {"zh": "轴对齐碰撞盒。"},
        "versedotorg/scenegraph/collision_interaction": {"zh": "指定一对碰撞体积应如何交互，见 collision_profile。"},
        "versedotorg/scenegraph/particle_system_component": {"zh": "在实体位置生成 particle_system；组件在场景中期间粒子系统持续模拟。依赖：实体上的 transform_component。"},
        "versedotorg/scenegraph/sound_component": {"zh": "在实体位置播放音效的组件。"},
        "versedotorg/scenegraph/mesh_component": {"zh": "在实体位置渲染网格。网格是一组多边形，可用于表现世界中的形状，如植被、地形装饰、建筑与道具等。"},
        "versedotorg/scenegraph/possessable_component": {"zh": "标记可被代理（agent）附身（possess）的实体。"},
        "versedotorg/scenegraph/entity_prefab": {"zh": "编辑器定义的预制体（prefab）的引用类型；只有生成的 digest 代码才应引用此类型。"},
        "versedotorg/scenegraph/icon_component": {"zh": "保存实体图标的组件。"},
        "versedotorg/scenegraph/entity_origin": {"zh": "为实体提供替代原点（默认为 transform_component）的类。"},
        "versedotorg/scenegraph/float_range": {"zh": "带最小值与最大值的范围；值要落在范围内须满足 min ≤ max。"},
        "versedotorg/scenegraph/execution_listenable": {"zh": "订阅或等待组件 TickEvents 各阶段的 DeltaTime 回调。"},
        "versedotorg/scenegraph/rarity": {"zh": "稀有度：供玩法与表现系统对事物进行分类与分级。"},
        "versedotorg/scenegraph/common_rarity": {"zh": "稀有度：常见（Common）。"},
        "versedotorg/scenegraph/uncommon_rarity": {"zh": "稀有度：非常见（Uncommon）。"},
        "versedotorg/scenegraph/rare_rarity": {"zh": "稀有度：稀有（Rare）。"},
        "versedotorg/scenegraph/epic_rarity": {"zh": "稀有度：史诗（Epic）。"},
        "versedotorg/scenegraph/legendary_rarity": {"zh": "稀有度：传说（Legendary）。"},
        "versedotorg/scenegraph/rarity_component": {"zh": "标注实体稀有度的组件。"},
        "versedotorg/scenegraph/stackable_component": {"zh": "挂到实体后，允许其与具有兼容组件的其他实体合并（堆叠）的组件。"},
        "versedotorg/scenegraph/change_stack_size_result": {"zh": "更改堆叠数量的结果。"},
        "versedotorg/scenegraph/change_max_stack_size_result": {"zh": "更改最大堆叠数量的结果。"},
        "versedotorg/scenegraph/basic_stackable_component": {"zh": "基础堆叠组件。"},
        "versedotorg/scenegraph/easeable": {"zh": "用于触发缓动行为的接口。"},
        "versedotorg/scenegraph/scene_event": {"zh": "可通过场景图发送的事件。"},
        "versedotorg/scenegraph/origin": {"zh": "为实体提供替代原点的接口（默认原点为其父实体），见 transform_component。"},
        "versedotorg/scenegraph/has_merge_rules": {"zh": "想参与实体可合并性检查的组件实现的「合并规则」接口。"},
        "versedotorg/scenegraph/entity_streaming_policy": {"zh": "实体的客户端流送模式。"},
        "versedotorg/scenegraph/children_streaming_policy": {"zh": "子实体的客户端流送模式。"},
        "versedotorg/scenegraph/collisionchannels/stationary": {"zh": "碰撞通道：静态（stationary）物体。"},
        "versedotorg/scenegraph/collisionchannels/dynamic": {"zh": "碰撞通道：动态（dynamic）物体。"},
        "versedotorg/scenegraph/collisionchannels/avatar": {"zh": "碰撞通道：角色（avatar，玩家角色）。"},
        "versedotorg/scenegraph/collisionchannels/visibility": {"zh": "碰撞通道：可见性（visibility）。"},
        "versedotorg/scenegraph/collisionchannels/camera": {"zh": "碰撞通道：相机（camera）。"},
        "versedotorg/scenegraph/collisionchannels/physics": {"zh": "碰撞通道：物理（physics）。"},
        "versedotorg/scenegraph/keyframedmovement/easing_function": {"zh": "动画缓动函数的基类。"},
        "versedotorg/scenegraph/keyframedmovement/cubic_bezier_easing_function": {"zh": "三次贝塞尔缓动函数，基础缓动值参见 CubicBezierEasingFunctions。"},
        "versedotorg/scenegraph/keyframedmovement/linear_easing_function": {"zh": "线性缓动：动画匀速运动。"},
        "versedotorg/scenegraph/keyframedmovement/ease_cubic_bezier_easing_function": {"zh": "缓动：起步慢、加速、结尾减速（结尾略慢于开始）。"},
        "versedotorg/scenegraph/keyframedmovement/ease_in_cubic_bezier_easing_function": {"zh": "缓入：起步慢，逐渐加速。"},
        "versedotorg/scenegraph/keyframedmovement/ease_out_cubic_bezier_easing_function": {"zh": "缓出：起步快，逐渐减速。"},
        "versedotorg/scenegraph/keyframedmovement/ease_in_out_cubic_bezier_easing_function": {"zh": "缓入缓出：类似 Ease，但首尾速度对称。"},
        "versedotorg/scenegraph/keyframedmovement/keyframed_movement_playback_mode": {"zh": "控制动画的播放方式。"},
        "versedotorg/scenegraph/keyframedmovement/oneshot_keyframed_movement_playback_mode": {"zh": "播放一次后停止。"},
        "versedotorg/scenegraph/keyframedmovement/loop_keyframed_movement_playback_mode": {"zh": "播放一次后无限重复。"},
        "versedotorg/scenegraph/keyframedmovement/pingpong_keyframed_movement_playback_mode": {"zh": "连续播放，在两端反向往复。"},
        "versedotorg/scenegraph/keyframedmovement/keyframed_movement_delta": {"zh": "表示一段时间内姿态与缩放的变化量。"},
        "versedotorg/scenegraph/keyframedmovement/keyframed_movement_component": {"zh": "为实体提供传送与基于关键帧的简单动画；动画在物理前置（Pre-Physics）tick 阶段播放。"},
    },
}

import os as _os, sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
from scene_cells_extra import EXTRA_CELLS
PACK["known_cells"].update(EXTRA_CELLS)
