# -*- coding: utf-8 -*-
# UnrealEngine.com 模块内容包
PACKS = [
    {
        "outdir": "02_UnrealEngine.com", "module_slug": "unrealenginedotcom",
        "overview_title": "UnrealEngine.com module", "overview_grade": "B",
        "overview_url": "https://dev.epicgames.com/documentation/fortnite/verse-api/unrealenginedotcom",
        "overview": {"zh": "引擎向的通用模块集：任务、物品栏、Web API、输入、诊断、JSON、技能等；Temporary 子空间存放仍在过渡期的 UI/Curves/Diagnostics/SpatialMath。"},
        "submodules": [
            {"name": "Conversations", "link": "010_Conversations/_overview.md", "zh": "官方页面当前无内容。"},
            {"name": "Progression", "link": "020_Progression/_overview.md", "zh": "任务系统：分类、目标与奖励。"},
            {"name": "Itemization", "link": "030_Itemization/_overview.md", "zh": "物品与物品栏：组件、事件与结果/错误。"},
            {"name": "WebAPI", "link": "040_WebAPI/_overview.md", "zh": "从 Verse 调用后端 Web 服务。"},
            {"name": "Temporary", "link": "050_Temporary/_overview.md", "zh": "过渡期 API：UI/Curves/Diagnostics/SpatialMath。"},
            {"name": "Social", "link": "060_Social/_overview.md", "zh": "派对成员信息。"},
            {"name": "JSON", "link": "070_JSON/_overview.md", "zh": "JSON 解析。"},
            {"name": "BasicShapes", "link": "080_BasicShapes/_overview.md", "zh": "基础几何形状。"},
            {"name": "Abilities", "link": "090_Abilities/_overview.md", "zh": "技能框架：ability/effect/context。"},
            {"name": "ControlInput", "link": "100_ControlInput/_overview.md", "zh": "玩家输入管理（与 Verse.org/Input 平行的实现）。"},
            {"name": "Assets", "link": "110_Assets/_overview.md", "zh": "生成粒子系统。"},
        ],
        "sub_outdirs": {
            "unrealenginedotcom/progression": "02_UnrealEngine.com/020_Progression",
            "unrealenginedotcom/itemization": "02_UnrealEngine.com/030_Itemization",
            "unrealenginedotcom/webapi": "02_UnrealEngine.com/040_WebAPI",
            "unrealenginedotcom/temporary": "02_UnrealEngine.com/050_Temporary",
            "unrealenginedotcom/social": "02_UnrealEngine.com/060_Social",
            "unrealenginedotcom/json": "02_UnrealEngine.com/070_JSON",
            "unrealenginedotcom/basicshapes": "02_UnrealEngine.com/080_BasicShapes",
            "unrealenginedotcom/abilities": "02_UnrealEngine.com/090_Abilities",
            "unrealenginedotcom/controlinput": "02_UnrealEngine.com/100_ControlInput",
            "unrealenginedotcom/assets": "02_UnrealEngine.com/110_Assets",
        },
        "known_prefix": [
            ["Entities are the base object in the SceneGraph.",
             "实体是 SceneGraph 的基础对象：体验中的对象由一个或多个实体构成；实体有层级，可用 GetParent 查询父实体、AddEntities 添加子实体；行为通过组件添加（AddComponents）；结构与内容动态可变。派生自 entity 的类即预制体（prefab），主要由编辑器生成；官方强烈建议逻辑写在组件而非 entity 类里，便于重构。"],
        ],
        "known_cells": {
            "Controls widget rendering order. Greater values will be draw in front of lesser values.":
                "控件渲染顺序；值越大越靠前绘制。",
        },
        "entries": {
            "unrealenginedotcom/progression/quest_category": {"zh": "任务 UI 中的分类。"},
            "unrealenginedotcom/progression/basic_quest": {"zh": "标准任务：遵循「做 X 得 Y」范式。自动完成——当 Objective.IsComplete() 成功时自动调用 Complete()；自动发奖——完成时经 GetRecipients() 与 GrantReward() 向符合条件的参与者发放奖励。"},
            "unrealenginedotcom/progression/quest_objective": {"zh": "所有任务目标的抽象基类。"},
            "unrealenginedotcom/progression/grant_quest_reward_error": {"zh": "无法发放奖励时返回的错误。"},
            "unrealenginedotcom/progression/quest_reward": {"zh": "所有任务奖励的抽象基类。"},
            "unrealenginedotcom/progression/entitlement_quest_reward": {"zh": "向每个符合条件的参与者授予一个 entitlement（授权项目）。"},
            "unrealenginedotcom/progression/progress_quest_objective": {"zh": "追踪到所需计数的数值进度；Progress ≥ RequiredCount 时完成。"},
            "unrealenginedotcom/progression/has_quest_presentation": {"zh": "在任务类上实现此接口，可自定义其在任务 UI 中的展示。"},
            "unrealenginedotcom/itemization/add_item_result": {"zh": "添加物品的结果。"},
            "unrealenginedotcom/itemization/remove_item_result": {"zh": "移除物品的结果。"},
            "unrealenginedotcom/itemization/equip_item_result": {"zh": "装备物品的结果。"},
            "unrealenginedotcom/itemization/unequip_item_result": {"zh": "卸下物品的结果。"},
            "unrealenginedotcom/itemization/find_inventory_event": {"zh": "添加物品时，find_inventory_event 作为第一道流程向下发送，用于为物品寻找最合适的物品栏；add_item_query_event 可否决物品栏选择（向上发送）。"},
            "unrealenginedotcom/itemization/add_item_error": {"zh": "添加物品失败时返回的错误。"},
            "unrealenginedotcom/itemization/add_item_query_event": {"zh": "添加物品时，find_inventory_event 先向下发送以寻找最佳物品栏；add_item_query_event 可否决物品栏选择——从物品栏（向祖先）向上、并从物品实体（向子级）向下发送。"},
            "unrealenginedotcom/itemization/remove_item_error": {"zh": "移除物品失败时返回的错误。"},
            "unrealenginedotcom/itemization/remove_item_query_event": {"zh": "可用于否决物品移除：从物品栏（向祖先）向上、并从物品实体（向子级）向下发送。"},
            "unrealenginedotcom/itemization/inventory_component": {"zh": "物品栏组件持有物品。带有物品栏组件的实体即视为拥有物品栏；它控制哪些物品可以进出，并决定物品能否被装备。"},
            "unrealenginedotcom/itemization/item_category": {"zh": "用于给物品分类。"},
            "unrealenginedotcom/itemization/change_equipped_result": {"zh": "更改已装备物品的结果。"},
            "unrealenginedotcom/itemization/change_inventory_result": {"zh": "更改物品栏的结果。"},
            "unrealenginedotcom/itemization/equip_item_error": {"zh": "装备物品失败时返回的错误。"},
            "unrealenginedotcom/itemization/equip_item_query_event": {"zh": "装备物品时可用于否决装备：从物品栏（向祖先）向上、并从物品实体（向子级）向下发送。"},
            "unrealenginedotcom/itemization/unequip_item_error": {"zh": "卸下物品失败时返回的错误。"},
            "unrealenginedotcom/itemization/unequip_item_query_event": {"zh": "卸下物品时可用于否决卸下：从物品栏（向祖先）向上、并从物品实体（向子级）向下发送。"},
            "unrealenginedotcom/itemization/item_component": {"zh": "使用此组件的实体应视为物品；与物品栏交互必需。"},
            "unrealenginedotcom/webapi/client_id": {"zh": "WebAPI 的 client_id：授权用户在自己的模块中派生它，派生类的 Verse 类路径即后端服务中映射到端点的配置键。警告：不要把派生的 client_id 设为 public——它是你后端的私钥。示例：my_client_id := class(client_id)，MyClient := MakeClient(my_client_id)。"},
            "unrealenginedotcom/webapi/client": {"zh": "WebAPI 客户端。"},
            "unrealenginedotcom/webapi/response": {"zh": "WebAPI 响应。"},
            "unrealenginedotcom/webapi/body_response": {"zh": "带响应体的 WebAPI 响应。"},
            "unrealenginedotcom/webapi/makeclient": {"zh": "构造 WebAPI 客户端。"},
            "unrealenginedotcom/temporary/sortby": {"zh": "用 Less 对 Array 稳定排序：Less 成功表示 Left 应排在 Right 之前。"},
            "unrealenginedotcom/social/party_member_info": {"zh": "派对成员的信息；未来版本可能扩展更多字段。"},
            "unrealenginedotcom/json/value": {"zh": "JSON 值类型。"},
            "unrealenginedotcom/json/parse": {"zh": "解析 JSON 字符串，返回包含其内容的 value。",
                "example": "if (V := Parse(\"{\\\"a\\\":1}\")):\\n    Print(\"解析成功\")"},
            "unrealenginedotcom/basicshapes/cube": {"zh": "基础形状：立方体。"},
            "unrealenginedotcom/basicshapes/sphere": {"zh": "基础形状：球体。"},
            "unrealenginedotcom/basicshapes/plane": {"zh": "基础形状：平面。"},
            "unrealenginedotcom/basicshapes/cone": {"zh": "基础形状：圆锥。"},
            "unrealenginedotcom/basicshapes/cylinder": {"zh": "基础形状：圆柱。"},
            "unrealenginedotcom/abilities/ability_context": {"zh": "技能激活时传入的数据：谁发起、谁协助、击中了什么。子类化它可为自定义技能效果提供上下文。"},
            "unrealenginedotcom/abilities/ability_effect": {"zh": "预制体：为技能与玩法逻辑提供集中处理位置。"},
            "unrealenginedotcom/abilities/ability/ability(context_type,ability_effect_type)": {"zh": "存在于场景图中，是技能的高层描述：知道技能能否运行、冷却、距离与目标要求等。"},
            "unrealenginedotcom/abilities/cancel_reason": {"zh": "技能取消原因。"},
            "unrealenginedotcom/abilities/ability_ended": {"zh": "技能结束相关。"},
            "unrealenginedotcom/abilities/ability_removed_from_scene": {"zh": "技能被移出场景相关。"},
            "unrealenginedotcom/abilities/ability_effect_component": {"zh": "Ability 预制体实体上的保证组件，处理技能生命周期。"},
            "unrealenginedotcom/abilities/makeabilityeffectcomponent": {"zh": "构造 ability_effect_component。"},
            "unrealenginedotcom/abilities/ability": {"zh": "存在于场景图中，是技能的高层描述：知道技能能否运行、冷却、距离与目标要求等（构造函数）。"},
            "unrealenginedotcom/controlinput/input_events/input_events(t)": {"zh": "用户输入事件的容器，可订阅。用 GetPlayerInput / GetInputEvents 获取某玩家的 input_events；低层通知：DetectionBeginEvent/DetectionOngoingEvent/DetectionEndEvent；高层通知：ActivationTriggeredEvent/ActivationCanceledEvent。"},
            "unrealenginedotcom/controlinput/player_input": {"zh": "玩家输入相关设置与功能的主管理类。"},
            "unrealenginedotcom/controlinput/input_events": {"zh": "用户输入事件容器的构造重载（同 input_events(t)）。"},
            "unrealenginedotcom/controlinput/getplayerinput": {"zh": "访问玩家的输入相关数据与设置。"},
            "unrealenginedotcom/assets/spawnparticlesystem": {"zh": "生成粒子系统。"},
            "unrealenginedotcom/assets/spawnparticlesystem-1": {"zh": "生成粒子系统（重载）。"},
        },
    },
    {
        "outdir": "02_UnrealEngine.com/050_Temporary", "module_slug": "unrealenginedotcom/temporary",
        "overview_title": "Temporary module", "overview_grade": "A",
        "overview_url": "https://dev.epicgames.com/documentation/fortnite/verse-api/unrealenginedotcom/temporary",
        "overview": {"zh": "过渡期 API 子空间：UI、Curves、Diagnostics、SpatialMath。这些 API 仍处过渡阶段，未来可能被 Verse.org 侧的对应体系取代。"},
        "submodules": [
            {"name": "UI", "link": "010_UI/_overview.md", "zh": "在玩家屏幕上构建界面的控件与容器。"},
            {"name": "Curves", "link": "020_Curves/_overview.md", "zh": "可编辑曲线。"},
            {"name": "Diagnostics", "link": "030_Diagnostics/_overview.md", "zh": "日志与调试绘制。"},
            {"name": "SpatialMath", "link": "040_SpatialMath/_overview.md", "zh": "官方页面当前无内容。"},
        ],
        "sub_outdirs": {
            "unrealenginedotcom/temporary/ui": "02_UnrealEngine.com/050_Temporary/010_UI",
            "unrealenginedotcom/temporary/curves": "02_UnrealEngine.com/050_Temporary/020_Curves",
            "unrealenginedotcom/temporary/diagnostics": "02_UnrealEngine.com/050_Temporary/030_Diagnostics",
        },
        "entries": {
            "unrealenginedotcom/temporary/ui/player_ui": {"zh": "向玩家 UI 添加/移除控件的主接口。"},
            "unrealenginedotcom/temporary/ui/widget": {"zh": "绘制在玩家屏幕上的一切 UI 元素的基类。"},
            "unrealenginedotcom/temporary/ui/player_ui_slot": {"zh": "widget 创建时的配置选项。"},
            "unrealenginedotcom/temporary/ui/widget_message": {"zh": "widget 事件所携带的参数。"},
            "unrealenginedotcom/temporary/ui/anchors": {"zh": "widget 的锚点决定其相对父级的位置与尺寸；范围从 (0.0, 0.0)（左上）到 (1.0, 1.0)（右下）。"},
            "unrealenginedotcom/temporary/ui/margin": {"zh": "widget 与相邻控件之间每条边的外间距；1.0 单位为 1080p 分辨率下一个像素的宽度。"},
            "unrealenginedotcom/temporary/ui/button": {"zh": "按钮容器：包含单个子控件槽，点击时触发 OnClick 事件。"},
            "unrealenginedotcom/temporary/ui/button_slot": {"zh": "按钮控件的槽位。"},
            "unrealenginedotcom/temporary/ui/canvas": {"zh": "画布容器：允许在其槽位中任意摆放控件。"},
            "unrealenginedotcom/temporary/ui/canvas_slot": {"zh": "画布控件的槽位。"},
            "unrealenginedotcom/temporary/ui/color_block": {"zh": "纯色控件。"},
            "unrealenginedotcom/temporary/ui/texture_block": {"zh": "显示贴图的控件。"},
            "unrealenginedotcom/temporary/ui/material_block": {"zh": "显示材质的控件。"},
            "unrealenginedotcom/temporary/ui/overlay": {"zh": "叠层容器：多个控件相互堆叠。"},
            "unrealenginedotcom/temporary/ui/overlay_slot": {"zh": "叠层控件的槽位。"},
            "unrealenginedotcom/temporary/ui/stack_box": {"zh": "堆叠容器：将一组控件垂直或水平排列。"},
            "unrealenginedotcom/temporary/ui/stack_box_slot": {"zh": "堆叠控件的槽位。"},
            "unrealenginedotcom/temporary/ui/text_base": {"zh": "文本控件的基类。"},
            "unrealenginedotcom/temporary/ui/getplayerui": {"zh": "返回与 Player 关联的 player_ui；无关联则失败。"},
            "unrealenginedotcom/temporary/ui/makecanvasslot": {"zh": "为固定位置控件构造画布槽位。若设置 Size 则据此计算 Offsets 且 SizeToContent=false；未设 Size 则 Right/Bottom 置零不使用、控件尺寸自动计算且 SizeToContent=true。控件不设锚点，父级缩放时不移动（Anchors 置零）。"},
            "unrealenginedotcom/temporary/ui/ui_input_mode": {"zh": "控件输入消费模式。"},
            "unrealenginedotcom/temporary/ui/widget_visibility": {"zh": "由 widget.SetVisibility 使用，决定控件在界面中的显示方式。"},
            "unrealenginedotcom/temporary/ui/orientation": {"zh": "控件朝向模式。"},
            "unrealenginedotcom/temporary/ui/horizontal_alignment": {"zh": "控件水平对齐模式。"},
            "unrealenginedotcom/temporary/ui/vertical_alignment": {"zh": "控件垂直对齐模式。"},
            "unrealenginedotcom/temporary/ui/image_tiling": {"zh": "贴图平铺选项值。"},
            "unrealenginedotcom/temporary/ui/text_justification": {"zh": "文本对齐值：Left——按当前文化逻辑靠左；Center——居中；Right——逻辑靠右。区域文化为从右向左时 Left/Right 会互换。"},
            "unrealenginedotcom/temporary/ui/text_overflow_policy": {"zh": "文本溢出策略：Clip——溢出部分被裁剪；Ellipsis——溢出部分以省略号替代。"},
            "unrealenginedotcom/temporary/ui/text_wrapping_policy": {"zh": "文本换行策略：LineBreak——仅在换行迭代点断行；PerCharacter——可在任意字符后断行。"},
            "unrealenginedotcom/temporary/curves/editable_curve": {"zh": "可在编辑器中编辑的曲线。"},
            "unrealenginedotcom/temporary/diagnostics/debug_draw_channel": {"zh": "定义调试绘制通道的基类。"},
            "unrealenginedotcom/temporary/diagnostics/debug_draw": {"zh": "在屏幕上绘制调试形状的类。"},
            "unrealenginedotcom/temporary/diagnostics/log_channel": {"zh": "定义日志通道的基类；打印消息到日志时，通道类名会作为前缀加在输出消息上。"},
            "unrealenginedotcom/temporary/diagnostics/log": {"zh": "向默认日志发送消息的类。"},
            "unrealenginedotcom/temporary/diagnostics/debug_draw_duration_policy": {"zh": "描述绘制时长的预设策略枚举。"},
            "unrealenginedotcom/temporary/diagnostics/log_level": {"zh": "各日志命令可用的日志级别。"},
        },
    },
]

try:
    from ue_cells_extra import EXTRA_CELLS
    for _pk in PACKS:
        _pk.setdefault("known_cells", {}).update(EXTRA_CELLS)
except ImportError:
    pass
