# -*- coding: utf-8 -*-
# Verse 核心模块内容包：slug → 中文对照（导语翻译或页面说明）+ 示例/补充
PACK = {
    "outdir": "01_Verse.org/010_Verse",
    "module_slug": "versedotorg/verse",
    "overview_title": "Verse module",
    "overview_grade": "B",
    "overview_url": "https://dev.epicgames.com/documentation/fortnite/verse-api/versedotorg/verse",
    "overview": {"zh": "Verse 语言核心模块：运算符、数学函数、字符串/诊断/结果类型、事件接口与时间函数。"},
    "submodules": [{"name": "Easing", "link": "010_Easing/_overview.md",
                    "zh": "缓动插值函数族（Linear/Ease/EaseIn/EaseOut/EaseInOut/CubicBezier）。"}],
    "sub_outdirs": {"versedotorg/verse/easing": "01_Verse.org/010_Verse/010_Easing"},
    "entries": {
        # ---- 已完成页（仅进总览表，不重写正文）----
        "versedotorg/verse/print": {"zh": "把 Message 写入专用 Print 日志，并在客户端屏幕以 Color 显示 Duration 秒。"},
        "versedotorg/verse/print-1": {"zh": "Print 的 message（可本地化文本）重载。"},
        "versedotorg/verse/print-2": {"zh": "Print 的 diagnostic（诊断）重载。"},
        "versedotorg/verse/event": {"zh": "参数化构造：按载荷类型 t 创建可重复触发的事件。"},
        "versedotorg/verse/event-1": {"zh": "event 的无载荷构造重载。"},
        "versedotorg/verse/event/event(t)": {"zh": "可重复、按次序触发的参数化事件：Await 等待、Signal 触发。"},
        "versedotorg/verse/listenable": {"zh": "参数化接口构造：组合 awaitable 与 subscribable（持续订阅广播）。"},
        "versedotorg/verse/listenable-1": {"zh": "listenable 的无参数构造重载。"},
        "versedotorg/verse/operatorequals": {"zh": "可失败的相等比较：相等则成功并返回左值。"},
        # ---- 类/结构体/接口 ----
        "versedotorg/verse/diagnostic": {"zh": "不透明的诊断消息，只出现在诊断日志中。其格式可能随时变化且无法被 Verse 代码检查。"},
        "versedotorg/verse/locale": {"zh": "用于 message 本地化的区域设置。"},
        "versedotorg/verse/message": {"zh": "可本地化的文本消息。"},
        "versedotorg/verse/classifiable_subset/classifiable_subset(element_type)": {"zh": "classifiable_subset 是容纳一组元素、可按标签层级评估分类的容器。"},
        "versedotorg/verse/modifier_stack/modifier_stack(t)": {"zh": "修饰符栈：按顺序应用修饰符。"},
        "versedotorg/verse/cancelable": {"zh": "由可取消操作实现：持有它即可取消对应的进行中操作。"},
        "versedotorg/verse/disposable": {"zh": "由实例生命周期有限（可释放）的类实现。"},
        "versedotorg/verse/enableable": {"zh": "由实例可被启用/禁用的类实现。"},
        "versedotorg/verse/invalidatable": {"zh": "由实例可能随时失效的类实现。"},
        "versedotorg/verse/showable": {"zh": "由实例可改变可见性的类实现。"},
        "versedotorg/verse/inf": {"zh": "浮点正无穷常量（IEEE 754 Inf）。"},
        "versedotorg/verse/nan": {"zh": "浮点非数常量（IEEE 754 NaN），表示无效的浮点运算结果。"},
        "versedotorg/verse/pifloat": {"zh": "浮点圆周率 π 常量。"},
        # ---- 函数：结果/诊断/事件接口 ----
        "versedotorg/verse/result": {"zh": "由「可为成功或失败的操作」的结果类实现。",
            "example": 'R := MakeError("存档失败")\nif (E := result[Error, string][R]):\n    Print("失败原因: {E}")'},
        "versedotorg/verse/makesuccess": {"zh": "构造一个表示成功的 result 实例。",
            "example": 'OK:result[string, string] = MakeSuccess("done")'},
        "versedotorg/verse/makeerror": {"zh": "构造一个携带错误信息的失败 result 实例。",
            "example": 'Bad:result[string, string] = MakeError("oops")'},
        "versedotorg/verse/todiagnostic": {"zh": "把任意 Verse 值转换成不透明的诊断消息。",
            "example": 'Print(ToDiagnostic(42))'},
        "versedotorg/verse/err": {"zh": "以错误消息 Message 立即中止 Verse 运行时。",
            "notes": "只在「绝不该发生」的防御性分支使用——它会终止整个脚本。"},
        "versedotorg/verse/signalable": {"zh": "带载荷、可被触发（signal）的事件实现的参数化接口。"},
        "versedotorg/verse/subscribable": {"zh": "带载荷、可被订阅（Subscribe 持续接收）的事件实现的参数化接口。",
            "example": 'E:event(int) = event(int){}\nE.Subscribe(Handler)   # Handler 为类成员函数'},
        "versedotorg/verse/subscribable-1": {"zh": "无载荷、可被订阅的事件实现的参数化接口。"},
        "versedotorg/verse/localize": {"zh": "按当前区域设置本地化 Message，生成字符串。",
            "example": 'S := Localize("greet.key", ["Name"], array["世界"])'},
        # ---- 函数：字符串/连接 ----
        "versedotorg/verse/concatenate": {"zh": "把嵌套数组压平：按顺序连接 Arr 里每个子数组的元素，返回一个新数组。",
            "example": 'Flat:int[] = Concatenate(array{array{1,2}, array{3}})   # {1, 2, 3}'},
        "versedotorg/verse/join": {"zh": "用 Separator 把 Element 数组拼接成一个 message（可本地化文本）。",
            "example": 'M := Join(array{"a", "b"}, "-")   # a-b'},
        "versedotorg/verse/join-1": {"zh": "用 Separator 把 Element 数组拼接成一个字符串。",
            "example": 'S := Join(array{"a", "b", "c"}, "-")   # a-b-c'},
        "versedotorg/verse/concatenatemaps": {"zh": "合并两个映射：M1 全部键值加上 M2 的键值（同键时以 M2 为准）。"},
        # ---- 函数：时间 ----
        "versedotorg/verse/getsecondssinceepoch": {"zh": "返回自 1970 年 1 月 1 日 UTC 起的秒数（Unix 时间戳），忽略闰秒。"},
        # ---- 函数：数学（A 级）----
        "versedotorg/verse/abs": {"zh": "返回 Value 的绝对值（int 版本）。",
            "example": "N := Abs(-3)   # 3"},
        "versedotorg/verse/abs-1": {"zh": "返回 Value 的绝对值（float 版本）。",
            "notes": "int 版本见 [Abs function](abs.md)。"},
        "versedotorg/verse/ceil": {"zh": "返回大于等于 Val 的最小 int（向上取整，rational 输入版本）。",
            "example": "N := Ceil(3.0)   # 3"},
        "versedotorg/verse/ceil-1": {"zh": "返回大于等于 Val 的最小 int（向上取整，float 输入版本）。非有限值时失败。",
            "example": "N := Ceil(1.2)   # 2"},
        "versedotorg/verse/floor": {"zh": "返回小于等于 Val 的最大 int（向下取整，rational 输入版本）。",
            "example": "N := Floor(3.0)   # 3"},
        "versedotorg/verse/floor-1": {"zh": "返回小于等于 Val 的最大 int（向下取整，float 输入版本）。非有限值时失败。",
            "example": "N := Floor(1.8)   # 1"},
        "versedotorg/verse/round": {"zh": "返回 Val 四舍五入到最近整数的 int；小数部分恰为 0.5 时取最近的偶数（IEEE-754 默认舍入）。非有限值时失败。",
            "example": "N := Round(1.5)   # 2（取偶）"},
        "versedotorg/verse/int": {"zh": "返回等于 Val 去掉小数部分的 int（向零取整）。",
            "example": "N := Int[2.9] or 0   # 2"},
        "versedotorg/verse/clamp": {"zh": "把 Val 限制在 A 与 B 之间（int 版本；健壮处理 A、B 顺序）。",
            "example": "N := Clamp(V, 0, 10)"},
        "versedotorg/verse/clamp-1": {"zh": "把 Val 限制在 A 与 B 之间（float 版本；健壮处理 A、B 顺序）。",
            "example": "F := Clamp(V, 0.0, 1.0)"},
        "versedotorg/verse/min": {"zh": "返回 X 和 Y 中的较小值（int 版本）。",
            "example": "N := Min(3, 7)   # 3"},
        "versedotorg/verse/min-1": {"zh": "返回 X 和 Y 中的较小值；任一为 NaN 时返回 NaN（float 版本）。",
            "example": "F := Min(0.5, 1.5)   # 0.5"},
        "versedotorg/verse/max": {"zh": "返回 X 和 Y 中的较大值（int 版本）。",
            "example": "N := Max(3, 7)   # 7"},
        "versedotorg/verse/max-1": {"zh": "返回 X 和 Y 中的较大值；任一为 NaN 时返回 NaN（float 版本）。",
            "example": "F := Max(0.5, 1.5)   # 1.5"},
        "versedotorg/verse/tostring": {"zh": "把 Val（float）转成字符串表示。",
            "example": 'S := ToString(3.14)'},
        "versedotorg/verse/tostring-1": {"zh": "把 Val（char）转成可打印的字符串表示。"},
        "versedotorg/verse/tostring-2": {"zh": "把 String 原样返回（string 的 ToString 重载）。"},
        "versedotorg/verse/tostring-3": {"zh": "把单个 Character（char）转成字符串。"},
        "versedotorg/verse/operatorquestionmark": {"zh": "logic 查询：Value 为 true 则成功，为 false 则失败——logic 接入失败上下文的标准写法。",
            "example": "Ready:logic = true\nif (Ready?):\n    Print(\"go\")"},
        "versedotorg/verse/operatorquestionmark-1": {"zh": "option 取值：Value 有值则成功并返回该值，为空则失败。",
            "example": "Opt:?int = option{7}\nif (V := Opt?):\n    Print(\"{V}\")"},
        # ---- 运算符（B）----
        "versedotorg/verse/operatorlessgreater": {"zh": "不相等比较：Lhs 与 Rhs 不相等则成功，相等则失败。与 [operator'=](operatorequals.md) 语义相反。"},
        "versedotorg/verse/prefixminus": {"zh": "整数取负（一元 -）。"},
        "versedotorg/verse/prefixminus-1": {"zh": "浮点取负（一元 -）。"},
        "versedotorg/verse/operatorplus": {"zh": "整数加法。"},
        "versedotorg/verse/operatorplus-1": {"zh": "浮点加法。"},
        "versedotorg/verse/operatorplus-2": {"zh": "数组拼接：返回 Lhs 与 Rhs 元素顺序连接的新数组。"},
        "versedotorg/verse/operatorplus-3": {"zh": "集合并集：返回包含 InSetL 与 InSetR 全部元素的新集合。"},
        "versedotorg/verse/operatorplus-4": {"zh": "拼接两个诊断消息。"},
        "versedotorg/verse/operatorplus-5": {"zh": "诊断消息与普通字符串拼接，结果为诊断消息。"},
        "versedotorg/verse/operatorplus-6": {"zh": "普通字符串与诊断消息拼接，结果为诊断消息。"},
        "versedotorg/verse/operatorminus": {"zh": "整数减法。"},
        "versedotorg/verse/operatorminus-1": {"zh": "浮点减法。"},
        "versedotorg/verse/operatorstar": {"zh": "整数乘法。"},
        "versedotorg/verse/operatorstar-1": {"zh": "浮点乘法。"},
        "versedotorg/verse/operatorstar-2": {"zh": "int 与 float 相乘，结果为 float。"},
        "versedotorg/verse/operatorstar-3": {"zh": "float 与 int 相乘，结果为 float。"},
        "versedotorg/verse/operatorslash": {"zh": "整数除法：返回 rational；除数为 0 时失败。"},
        "versedotorg/verse/operatorslash-1": {"zh": "浮点除法（除数为 0 结果为 Inf/NaN，不失败）。"},
        "versedotorg/verse/operatorplusequals": {"zh": "整数累加：等价于 set Lhs = Lhs + Rhs。"},
        "versedotorg/verse/operatorplusequals-1": {"zh": "浮点累加。"},
        "versedotorg/verse/operatorplusequals-2": {"zh": "数组累加：把 Rhs 的元素追加进 Lhs 数组。"},
        "versedotorg/verse/operatorminusequals": {"zh": "整数累减。"},
        "versedotorg/verse/operatorminusequals-1": {"zh": "浮点累减。"},
        "versedotorg/verse/operatorstarequals": {"zh": "整数累乘。"},
        "versedotorg/verse/operatorstarequals-1": {"zh": "浮点累乘。"},
        "versedotorg/verse/operator/equals": {"zh": "浮点累除。"},
        "versedotorg/verse/operatorgreater": {"zh": "整数大于比较（可失败）。"},
        "versedotorg/verse/operatorgreater-1": {"zh": "浮点大于比较（可失败）。"},
        "versedotorg/verse/operatorgreaterequals": {"zh": "整数大于等于比较（可失败）。"},
        "versedotorg/verse/operatorgreaterequals-1": {"zh": "浮点大于等于比较（可失败）。"},
        "versedotorg/verse/operatorless": {"zh": "整数小于比较（可失败）。"},
        "versedotorg/verse/operatorless-1": {"zh": "浮点小于比较（可失败）。"},
        "versedotorg/verse/operatorlessequals": {"zh": "整数小于等于比较（可失败）。"},
        "versedotorg/verse/operatorlessequals-1": {"zh": "浮点小于等于比较（可失败）。"},
        "versedotorg/verse/operator()": {"zh": "数组按索引取元素：越界则失败。"},
        "versedotorg/verse/operator()-1": {"zh": "数组按索引取元素重载（u 元素类型版本）。"},
        "versedotorg/verse/operator()-2": {"zh": "映射按键取值：键不存在则失败。"},
        "versedotorg/verse/operator()-3": {"zh": "映射按键取值重载。"},
        "versedotorg/verse/operator()-4": {"zh": "映射按键取值重载。"},
        "versedotorg/verse/weak_map": {"zh": "构造「键为弱引用对象」的映射类型（如以 player/session 为键的全局状态表）。",
            "notes": "标准用法见 [session class](../100_Simulation/session.md)。"},
        "versedotorg/verse/concatenatemaps": {"zh": "合并两个映射（M2 同键覆盖 M1）。", "example": 'M := ConcatenateMaps(map{"a":1}, map{"b":2})'},
        "versedotorg/verse/fitsinplayermap": {"zh": "判断该类型是否能用作 player 映射的键（涉及持久化限制）。"},
        "versedotorg/verse/classifiable_subset": {"zh": "构造可分类子集容器。"},
        "versedotorg/verse/makeclassifiablesubset": {"zh": "构造包含 InElements 的 classifiable_subset。"},
        "versedotorg/verse/bitand": {"zh": "按位与。"},
        "versedotorg/verse/bitor": {"zh": "按位或。"},
        "versedotorg/verse/bitxor": {"zh": "按位异或。"},
        "versedotorg/verse/bitnot": {"zh": "按位取反。"},
        # ---- 数学（B）----
        "versedotorg/verse/sqrt": {"zh": "返回 X 的平方根；X < 0.0 时返回 NaN。"},
        "versedotorg/verse/sin": {"zh": "返回 X 的正弦（X 为弧度）。"},
        "versedotorg/verse/cos": {"zh": "返回 X 的余弦（X 为弧度）。"},
        "versedotorg/verse/tan": {"zh": "返回 X 的正切（X 为弧度）。"},
        "versedotorg/verse/arcsin": {"zh": "返回 X 的反正弦（弧度）。"},
        "versedotorg/verse/arccos": {"zh": "返回 X 的反余弦（弧度）。"},
        "versedotorg/verse/arctan": {"zh": "返回 X 的反正切（弧度）。"},
        "versedotorg/verse/arctan-1": {"zh": "返回原点到点 (X, Y) 连线与 X 轴的夹角（弧度）。"},
        "versedotorg/verse/sinh": {"zh": "返回 X 的双曲正弦。"},
        "versedotorg/verse/cosh": {"zh": "返回 X 的双曲余弦。"},
        "versedotorg/verse/tanh": {"zh": "返回 X 的双曲正切。"},
        "versedotorg/verse/arsinh": {"zh": "返回 X 的反双曲正弦（X 有限时）。"},
        "versedotorg/verse/arcosh": {"zh": "返回 X 的反双曲余弦（X ≥ 1.0 时）。"},
        "versedotorg/verse/artanh": {"zh": "返回 X 的反双曲正切（X 有限时）。"},
        "versedotorg/verse/pow": {"zh": "返回 A 的 B 次幂。"},
        "versedotorg/verse/quotient": {"zh": "返回欧几里得除法 X/Y 的商。"},
        "versedotorg/verse/mod": {"zh": "返回欧几里得除法 X/Y 的余数。"},
        "versedotorg/verse/exp": {"zh": "返回 e 的 X 次幂（自然指数）。"},
        "versedotorg/verse/ln": {"zh": "返回 X 的自然对数。"},
        "versedotorg/verse/log": {"zh": "返回 X 的以 B 为底对数。"},
        "versedotorg/verse/lerp": {"zh": "在 From（t=0）与 To（t=1）之间线性插值/外推。"},
        "versedotorg/verse/sgn": {"zh": "返回 Val 的符号：正数 1、零 0、负数 -1（int 版本）。"},
        "versedotorg/verse/sgn-1": {"zh": "返回 Val 的符号（float 版本）。"},
        "versedotorg/verse/isalmostequal": {"zh": "若 Val1 与 Val2 的差在 AbsoluteTolerance 内则成功（浮点比较专用）。"},
        # ---- Easing 子模块 ----
        "versedotorg/verse/easing/linear": {"zh": "线性插值函数：动画匀速运动。"},
        "versedotorg/verse/easing/cubicbezier": {"zh": "构造三次贝塞尔插值函数。"},
        "versedotorg/verse/easing/ease": {"zh": "缓动插值：起步慢、加速、结尾再减速（结尾略慢于开始）。"},
        "versedotorg/verse/easing/easein": {"zh": "缓入插值：起步慢，逐渐加速。"},
        "versedotorg/verse/easing/easeout": {"zh": "缓出插值：起步快，逐渐减速。"},
        "versedotorg/verse/easing/easeinout": {"zh": "缓入缓出插值：起步慢、中间快、结尾慢。"},
    },
    # Easing 子模块总览
    "submodule_overviews": [
        {"slug": "versedotorg/verse/easing", "outdir": "01_Verse.org/010_Verse/010_Easing",
         "title": "Easing module", "zh": "缓动插值函数族：为动画/关键帧运动提供速度曲线。"}
    ],
}
